version: '3.4'
services:
  daemon:
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: docker.io/ccarney16/pterodactyl-daemon:latest
    ports:
      - 2022:2022
      - 8080:8080
    privileged: true
    restart: always
    volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}:${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - ./configs/daemon:/etc/pterodactyl
      - ./configs/letsencrypt:/etc/letsencrypt:ro
      - ./configs/certs:/etc/certs:ro
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.daemon-reload.schedule: "${DAEMON_RELOAD_SCHEDULE:-0 30 0 * * *}"
      ofelia.job-exec.daemon-reload.command: "kill -15 1"
  certbot:
    command: renew
    image: docker.io/certbot/certbot:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/letsencrypt:/etc/letsencrypt
  cron:
    command: daemon --docker
    depends_on:
      certbot:
        condition: service_started
      daemon:
        condition: service_started
    image: docker.io/mcuadros/ofelia:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.le-renew.schedule: "0 0 0 * * *"
      ofelia.job-run.le-renew.container: pterodactyl_certbot_1
    network_mode: none
    privileged: true
    restart: always
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}